name: Generate documentation with doxygen

on:
    push:
        tags:
          - 'v*'

jobs:
    doxygen:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install Doxygen
          run: sudo apt-get install doxygen

        - name: Generate documentation
          run: doxygen Doxyfile

        - name: Save generated documentation
          uses: actions/upload-artifact@v2
          with:
            name: documentation
            path: html
